php artisan make:model TaiKhoan
php artisan make:model LoaiXe
php artisan make:model HangXe
php artisan make:model ModelXe
php artisan make:model PhienBanXe
php artisan make:model MauNgoaiThat
php artisan make:model MauNoiThat
php artisan make:model ThongSoKyThuatXe
php artisan make:model NhanVien
php artisan make:model KhachHang
php artisan make:model NhaCungCap
php artisan make:model DatHang
php artisan make:model ChiTietDatHang
php artisan make:model HoaDonNhapXe
php artisan make:model ChiTietNhapXe
php artisan make:model ChuDeBaiViet
php artisan make:model BaiViet
php artisan make:model BinhLuan